# Generated by Django 5.1.5 on 2025-11-02 21:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='Krótki opis')),
                ('author_name', models.CharField(max_length=100, verbose_name='Autor')),
                ('published_date', models.DateField(verbose_name='Data publikacji')),
                ('content_markdown', models.TextField(verbose_name='Treść (Markdown)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Post na blogu',
                'verbose_name_plural': 'Posty na blogu',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=200, verbose_name='Krótki opis')),
                ('description', models.TextField(verbose_name='Opis')),
                ('icon', models.CharField(default='fas fa-code', help_text='Wpisz klasę ikony z Font Awesome (np. fas fa-code, fab fa-python)', max_length=50, verbose_name='Ikona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kursy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Możesz używać Markdown, w tym bloków kodu. Przykład kodu: ```python\nprint('Hello')\n```", verbose_name='Treść pytania')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('explanation', models.TextField(blank=True, help_text='Wyjaśnienie poprawnych odpowiedzi', verbose_name='Wyjaśnienie')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł kursu wideo')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=300, verbose_name='Krótki opis')),
                ('thumbnail', models.ImageField(help_text='Zalecany rozmiar: 1280x720px', upload_to='video_thumbnails/', verbose_name='Miniaturka')),
                ('youtube_playlist_url', models.URLField(help_text='Wklej pełny URL do playlisty YouTube', verbose_name='Link do playlisty YouTube')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Kurs wideo',
                'verbose_name_plural': 'Kursy wideo',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('content_markdown', models.TextField(blank=True, null=True, verbose_name='Treść (Markdown)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main_app.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Treść tekstowa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='main_app.lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name': 'Treść lekcji',
                'verbose_name_plural': 'Treści lekcji',
            },
        ),
        migrations.CreateModel(
            name='PracticalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('content_markdown', models.TextField(verbose_name='Treść zadania (Markdown)')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='Treść zadania (HTML)')),
                ('instructions_markdown', models.TextField(blank=True, verbose_name='Instrukcje (Markdown)')),
                ('instructions_html', models.TextField(blank=True, editable=False, verbose_name='Instrukcje (HTML)')),
                ('example_markdown', models.TextField(blank=True, verbose_name='Przykład (Markdown)')),
                ('example_html', models.TextField(blank=True, editable=False, verbose_name='Przykład (HTML)')),
                ('hints_markdown', models.TextField(blank=True, verbose_name='Wskazówki (Markdown)')),
                ('hints_html', models.TextField(blank=True, editable=False, verbose_name='Wskazówki (HTML)')),
                ('solution_markdown', models.TextField(blank=True, verbose_name='Rozwiązanie (Markdown)')),
                ('solution_html', models.TextField(blank=True, editable=False, verbose_name='Rozwiązanie (HTML)')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practicaltask', to='main_app.lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name': 'Zadanie praktyczne',
                'verbose_name_plural': 'Zadania praktyczne',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Tekst odpowiedzi')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Poprawna odpowiedź')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main_app.question', verbose_name='Pytanie')),
            ],
            options={
                'verbose_name': 'Odpowiedź',
                'verbose_name_plural': 'Odpowiedzi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='main_app.lesson', verbose_name='Lekcja')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag', verbose_name='Tagi'),
        ),
    ]
