# Generated by Django 5.1.5 on 2026-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł projektu')),
                ('badge_icon', models.CharField(choices=[('fas fa-laptop-code', 'Web App'), ('fas fa-calculator', 'Kalkulator'), ('fas fa-cloud-sun', 'API'), ('fas fa-mobile-alt', 'Mobile App'), ('fas fa-gamepad', 'Gra'), ('fas fa-robot', 'AI/ML'), ('fas fa-database', 'Baza danych'), ('fas fa-terminal', 'CLI'), ('fas fa-puzzle-piece', 'Plugin'), ('fas fa-tools', 'Narzędzie')], default='fas fa-laptop-code', help_text="Ikona FontAwesome wyświetlana w badge'u", max_length=50, verbose_name="Ikona badge'a")),
                ('badge_text', models.CharField(default='Web App', help_text='Krótki tekst opisujący typ projektu (np. Web App, API)', max_length=50, verbose_name="Tekst badge'a")),
                ('description', models.TextField(max_length=300, verbose_name='Opis projektu')),
                ('technologies', models.CharField(help_text='Lista technologii oddzielona przecinkami (np. HTML, CSS, JavaScript)', max_length=300, verbose_name='Technologie')),
                ('live_demo_url', models.URLField(blank=True, help_text='URL do działającej wersji projektu (opcjonalne)', null=True, verbose_name='Link do Live Demo')),
                ('github_url', models.URLField(blank=True, help_text='URL do repozytorium GitHub (opcjonalne)', null=True, verbose_name='Link do GitHub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
